In [1]:
import pandas as pd
pd.set_option('display.max_rows', 100)

In [2]:
df = pd.read_csv('df_messed_dates.csv')

In [3]:
df.head()

,country,iso3,who_region,date,total_confirmed_cases,total_probable_cases,total_deaths,new_confirmed_cases,new_probable_cases,new_deaths
0,Benin,BEN,African Region,2022-06-24,3,0,0,3,0,0
1,Benin,BEN,African Region,2022-07-01,3,0,0,0,0,0
2,Benin,BEN,African Region,2022-07-08,3,0,0,0,0,0
3,Benin,BEN,African Region,2022-07-15,3,0,0,0,0,0
4,Benin,BEN,African Region,2022-07-22,3,0,0,0,0,0

In [4]:
mappings = list(df.groupby(['country', 'iso3', 'who_region']).groups.keys())
mappings = pd.DataFrame(mappings, columns=['country', 'iso3', 'who_region'])
mappings

                                country iso3                    who_region
0                               Andorra  AND               European Region
1                             Argentina  ARG        Region of the Americas
2                                 Aruba  ABW        Region of the Americas
3                             Australia  AUS        Western Pacific Region
4                               Austria  AUT               European Region
..                                  ...  ...                           ...
108                United Arab Emirates  ARE  Eastern Mediterranean Region
109            United States of America  USA        Region of the Americas
110                             Uruguay  URY        Region of the Americas
111  Venezuela (Bolivarian Republic of)  VEN        Region of the Americas
112                            Viet Nam  VNM        Western Pacific Region

[113 rows x 3 columns]

In [5]:
dates = list(df['date'].unique())
iso3 = list(df['iso3'].unique())

In [6]:
df.set_index(["date", 'iso3'], inplace=True)

In [7]:
new_index = pd.MultiIndex.from_product(df.index.levels)

In [8]:
new_index

MultiIndex([('2022-01-07', 'ABW'),
            ('2022-01-07', 'AND'),
            ('2022-01-07', 'ARE'),
            ('2022-01-07', 'ARG'),
            ('2022-01-07', 'AUS'),
            ('2022-01-07', 'AUT'),
            ('2022-01-07', 'BEL'),
            ('2022-01-07', 'BEN'),
            ('2022-01-07', 'BGR'),
            ('2022-01-07', 'BHR'),
            ...
            ('2023-07-18', 'SWE'),
            ('2023-07-18', 'THA'),
            ('2023-07-18', 'TTO'),
            ('2023-07-18', 'TUR'),
            ('2023-07-18', 'UKR'),
            ('2023-07-18', 'URY'),
            ('2023-07-18', 'USA'),
            ('2023-07-18', 'VEN'),
            ('2023-07-18', 'VNM'),
            ('2023-07-18', 'ZAF')],
           names=['date', 'iso3'], length=37290)

In [9]:
new_df = df.reindex(new_index)

In [10]:
new_df.reset_index(inplace=True)

In [11]:
new_df

,date,iso3,country,who_region,total_confirmed_cases,total_probable_cases,total_deaths,new_confirmed_cases,new_probable_cases,new_deaths
0,2022-01-07,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-01-07,AND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-01-07,ARE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-01-07,ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-01-07,AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
37285,2023-07-18,URY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37286,2023-07-18,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37287,2023-07-18,VEN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37288,2023-07-18,VNM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37289,2023-07-18,ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# remapping country names
new_df['country'] = new_df['iso3'].apply(lambda iso: mappings[mappings['iso3'] == iso].iloc[0]['country'])

In [13]:
# remapping who region
new_df['who_region'] = new_df['iso3'].apply(lambda iso: mappings[mappings['iso3'] == iso].iloc[0]['who_region'])

In [14]:
new_df.head(100)

,date,iso3,country,who_region,total_confirmed_cases,total_probable_cases,total_deaths,new_confirmed_cases,new_probable_cases,new_deaths
0,2022-01-07,ABW,Aruba,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-01-07,AND,Andorra,European Region,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-01-07,ARE,United Arab Emirates,Eastern Mediterranean Region,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-01-07,ARG,Argentina,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-01-07,AUS,Australia,Western Pacific Region,NaN,NaN,NaN,NaN,NaN,NaN
5,2022-01-07,AUT,Austria,European Region,NaN,NaN,NaN,NaN,NaN,NaN
6,2022-01-07,BEL,Belgium,European Region,NaN,NaN,NaN,NaN,NaN,NaN
7,2022-01-07,BEN,Benin,African Region,NaN,NaN,NaN,NaN,NaN,NaN
8,2022-01-07,BGR,Bulgaria,European Region,NaN,NaN,NaN,NaN,NaN,NaN
9,2022-01-07,BHR,Bahrain,Eastern Mediterranean Region,NaN,NaN,NaN,NaN,NaN,NaN
10,2022-01-07,BHS,Bahamas,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
11,2022-01-07,BIH,Bosnia and Herzegovina,European Region,NaN,NaN,NaN,NaN,NaN,NaN
12,2022-01-07,BMU,Bermuda,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
13,2022-01-07,BOL,Bolivia (Plurinational State of),Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
14,2022-01-07,BRA,Brazil,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
15,2022-01-07,BRB,Barbados,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
16,2022-01-07,CAF,Central African Republic,African Region,NaN,NaN,NaN,NaN,NaN,NaN
17,2022-01-07,CAN,Canada,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
18,2022-01-07,CHE,Switzerland,European Region,NaN,NaN,NaN,NaN,NaN,NaN
19,2022-01-07,CHL,Chile,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
20,2022-01-07,CHN,China,Western Pacific Region,NaN,NaN,NaN,NaN,NaN,NaN
21,2022-01-07,CMR,Cameroon,African Region,NaN,NaN,NaN,NaN,NaN,NaN
22,2022-01-07,COD,Democratic Republic of the Congo,African Region,NaN,NaN,NaN,NaN,NaN,NaN
23,2022-01-07,COG,Congo,African Region,NaN,NaN,NaN,NaN,NaN,NaN
24,2022-01-07,COL,Colombia,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
25,2022-01-07,CRI,Costa Rica,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
26,2022-01-07,CUB,Cuba,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
27,2022-01-07,CUW,CuraÃ§ao,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
28,2022-01-07,CYP,Cyprus,European Region,NaN,NaN,NaN,NaN,NaN,NaN
29,2022-01-07,CZE,Czechia,European Region,NaN,NaN,NaN,NaN,NaN,NaN
30,2022-01-07,DEU,Germany,European Region,NaN,NaN,NaN,NaN,NaN,NaN
31,2022-01-07,DNK,Denmark,European Region,NaN,NaN,NaN,NaN,NaN,NaN
32,2022-01-07,DOM,Dominican Republic,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
33,2022-01-07,ECU,Ecuador,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
34,2022-01-07,EGY,Egypt,Eastern Mediterranean Region,NaN,NaN,NaN,NaN,NaN,NaN
35,2022-01-07,ESP,Spain,European Region,NaN,NaN,NaN,NaN,NaN,NaN
36,2022-01-07,EST,Estonia,European Region,NaN,NaN,NaN,NaN,NaN,NaN
37,2022-01-07,FIN,Finland,European Region,NaN,NaN,NaN,NaN,NaN,NaN
38,2022-01-07,FRA,France,European Region,NaN,NaN,NaN,NaN,NaN,NaN
39,2022-01-07,GBR,The United Kingdom,European Region,NaN,NaN,NaN,NaN,NaN,NaN
40,2022-01-07,GEO,Georgia,European Region,NaN,NaN,NaN,NaN,NaN,NaN
41,2022-01-07,GHA,Ghana,African Region,NaN,NaN,NaN,NaN,NaN,NaN
42,2022-01-07,GIB,Gibraltar,European Region,NaN,NaN,NaN,NaN,NaN,NaN
43,2022-01-07,GLP,Guadeloupe,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
44,2022-01-07,GRC,Greece,European Region,NaN,NaN,NaN,NaN,NaN,NaN
45,2022-01-07,GRL,Greenland,European Region,NaN,NaN,NaN,NaN,NaN,NaN
46,2022-01-07,GTM,Guatemala,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
47,2022-01-07,GUM,Guam,Western Pacific Region,NaN,NaN,NaN,NaN,NaN,NaN
48,2022-01-07,GUY,Guyana,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
49,2022-01-07,HND,Honduras,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
50,2022-01-07,HRV,Croatia,European Region,NaN,NaN,NaN,NaN,NaN,NaN
51,2022-01-07,HUN,Hungary,European Region,NaN,NaN,NaN,NaN,NaN,NaN
52,2022-01-07,IDN,Indonesia,South-East Asia Region,NaN,NaN,NaN,NaN,NaN,NaN
53,2022-01-07,IND,India,South-East Asia Region,NaN,NaN,NaN,NaN,NaN,NaN
54,2022-01-07,IRL,Ireland,European Region,NaN,NaN,NaN,NaN,NaN,NaN
55,2022-01-07,IRN,Iran (Islamic Republic of),Eastern Mediterranean Region,NaN,NaN,NaN,NaN,NaN,NaN
56,2022-01-07,ISL,Iceland,European Region,NaN,NaN,NaN,NaN,NaN,NaN
57,2022-01-07,ISR,Israel,European Region,NaN,NaN,NaN,NaN,NaN,NaN
58,2022-01-07,ITA,Italy,European Region,NaN,NaN,NaN,NaN,NaN,NaN
59,2022-01-07,JAM,Jamaica,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
60,2022-01-07,JOR,Jordan,Eastern Mediterranean Region,NaN,NaN,NaN,NaN,NaN,NaN
61,2022-01-07,JPN,Japan,Western Pacific Region,NaN,NaN,NaN,NaN,NaN,NaN
62,2022-01-07,KOR,Republic of Korea,Western Pacific Region,NaN,NaN,NaN,NaN,NaN,NaN
63,2022-01-07,LBN,Lebanon,Eastern Mediterranean Region,NaN,NaN,NaN,NaN,NaN,NaN
64,2022-01-07,LBR,Liberia,African Region,NaN,NaN,NaN,NaN,NaN,NaN
65,2022-01-07,LKA,Sri Lanka,South-East Asia Region,NaN,NaN,NaN,NaN,NaN,NaN
66,2022-01-07,LTU,Lithuania,European Region,NaN,NaN,NaN,NaN,NaN,NaN
67,2022-01-07,LUX,Luxembourg,European Region,NaN,NaN,NaN,NaN,NaN,NaN
68,2022-01-07,LVA,Latvia,European Region,NaN,NaN,NaN,NaN,NaN,NaN
69,2022-01-07,MAF,Saint Martin,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
70,2022-01-07,MAR,Morocco,Eastern Mediterranean Region,NaN,NaN,NaN,NaN,NaN,NaN
71,2022-01-07,MCO,Monaco,European Region,NaN,NaN,NaN,NaN,NaN,NaN
72,2022-01-07,MDA,Republic of Moldova,European Region,NaN,NaN,NaN,NaN,NaN,NaN
73,2022-01-07,MEX,Mexico,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
74,2022-01-07,MLT,Malta,European Region,NaN,NaN,NaN,NaN,NaN,NaN
75,2022-01-07,MNE,Montenegro,European Region,NaN,NaN,NaN,NaN,NaN,NaN
76,2022-01-07,MOZ,Mozambique,African Region,NaN,NaN,NaN,NaN,NaN,NaN
77,2022-01-07,MTQ,Martinique,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
78,2022-01-07,NCL,New Caledonia,Western Pacific Region,NaN,NaN,NaN,NaN,NaN,NaN
79,2022-01-07,NGA,Nigeria,African Region,1.0,0.0,0.0,1.0,0.0,0.0
80,2022-01-07,NLD,Netherlands,European Region,NaN,NaN,NaN,NaN,NaN,NaN
81,2022-01-07,NOR,Norway,European Region,NaN,NaN,NaN,NaN,NaN,NaN
82,2022-01-07,NPL,Nepal,South-East Asia Region,NaN,NaN,NaN,NaN,NaN,NaN
83,2022-01-07,NZL,New Zealand,Western Pacific Region,NaN,NaN,NaN,NaN,NaN,NaN
84,2022-01-07,PAK,Pakistan,Eastern Mediterranean Region,NaN,NaN,NaN,NaN,NaN,NaN
85,2022-01-07,PAN,Panama,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
86,2022-01-07,PER,Peru,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
87,2022-01-07,PHL,Philippines,Western Pacific Region,NaN,NaN,NaN,NaN,NaN,NaN
88,2022-01-07,POL,Poland,European Region,NaN,NaN,NaN,NaN,NaN,NaN
89,2022-01-07,PRI,Puerto Rico,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
90,2022-01-07,PRT,Portugal,European Region,NaN,NaN,NaN,NaN,NaN,NaN
91,2022-01-07,PRY,Paraguay,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
92,2022-01-07,QAT,Qatar,Eastern Mediterranean Region,NaN,NaN,NaN,NaN,NaN,NaN
93,2022-01-07,ROU,Romania,European Region,NaN,NaN,NaN,NaN,NaN,NaN
94,2022-01-07,RUS,Russian Federation,European Region,NaN,NaN,NaN,NaN,NaN,NaN
95,2022-01-07,SAU,Saudi Arabia,Eastern Mediterranean Region,NaN,NaN,NaN,NaN,NaN,NaN
96,2022-01-07,SDN,Sudan,Eastern Mediterranean Region,NaN,NaN,NaN,NaN,NaN,NaN
97,2022-01-07,SGP,Singapore,Western Pacific Region,NaN,NaN,NaN,NaN,NaN,NaN
98,2022-01-07,SLV,El Salvador,Region of the Americas,NaN,NaN,NaN,NaN,NaN,NaN
99,2022-01-07,SMR,San Marino,European Region,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# adding zero values to the first day for each country where are NaNs
new_df.loc[new_df['date']=='2022-01-07'] = new_df.loc[new_df['date']=='2022-01-07'].fillna(0)

In [16]:
# sorting by country and Date
new_df.sort_values(by=['iso3', 'date'], inplace=True)

In [17]:
# forward fill NaN with previous values
new_df = new_df.fillna(method='ffill')

In [18]:
new_df

,date,iso3,country,who_region,total_confirmed_cases,total_probable_cases,total_deaths,new_confirmed_cases,new_probable_cases,new_deaths
0,2022-01-07,ABW,Aruba,Region of the Americas,0.0,0.0,0.0,0.0,0.0,0.0
113,2022-01-14,ABW,Aruba,Region of the Americas,0.0,0.0,0.0,0.0,0.0,0.0
226,2022-01-19,ABW,Aruba,Region of the Americas,0.0,0.0,0.0,0.0,0.0,0.0
339,2022-01-21,ABW,Aruba,Region of the Americas,0.0,0.0,0.0,0.0,0.0,0.0
452,2022-01-28,ABW,Aruba,Region of the Americas,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
36837,2023-07-11,ZAF,South Africa,African Region,5.0,0.0,0.0,0.0,0.0,0.0
36950,2023-07-12,ZAF,South Africa,African Region,5.0,0.0,0.0,0.0,0.0,0.0
37063,2023-07-14,ZAF,South Africa,African Region,5.0,0.0,0.0,0.0,0.0,0.0
37176,2023-07-17,ZAF,South Africa,African Region,5.0,0.0,0.0,0.0,0.0,0.0
37289,2023-07-18,ZAF,South Africa,African Region,5.0,0.0,0.0,0.0,0.0,0.0

In [19]:
new_df.to_csv('filled_data.csv', index=False)